### ISSUE TITLE
商品可以添加一个sku功能吗

### ISSUE THREAD

**Issue by zhuzaiBro** [newbee-ltd/newbee-mall-api-go#1]
老师，我想学习关于电商的知识，这个**sku规格价格组**能不能也加上去啊 @ZHENFENG13 @dalaohekele

**Comment by dalaohekele** [comment]
这个项目和原项目是配套的，作为学习框架的项目，如果想学习商城相关的项目可以看看这个https://github.com/youlaitech/youlai-mall

**Comment by dalaohekele** [comment]
> 老师，我想学习关于电商的知识，这个**sku规格价格组**能不能也加上去啊 @ZHENFENG13 @dalaohekele

https://github.com/youlaitech/youlai-mall

> 老师，我想学习关于电商的知识，这个**sku规格价格组**能不能也加上去啊 @ZHENFENG13 @dalaohekele



> 老师，我想学习关于电商的知识，这个**sku规格价格组**能不能也加上去啊 @ZHENFENG13 @dalaohekele

这个项目和原项目是配套的，作为学习框架的项目，并不能作为电商系统相关知识来学习。
如果想学习商城相关的项目可以看看这个https://github.com/youlaitech/youlai-mall
