### ISSUE TITLE
用户登陆的时候少了一步MD5加密的过程

### ISSUE THREAD

**Issue by Blue-967** [newbee-ltd/newbee-mall-api-go#2]

**Comment by Blue-967** [comment]
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/67788660/206397405-d48b1c26-f4bd-4e3b-80ac-7cee97547e09.png">

**Comment by Blue-967** [comment]
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/67788660/206397882-bbab735d-ba27-41b1-9bcb-8fb8e63d957c.png">

**Comment by Blue-967** [comment]
还是说前端有加密的过程  我是用postman调试的？

**Comment by ZHENFENG13** [comment]
前端传加密后的字符串过来
