### ISSUE TITLE
./server.exe 进入http://localhost:8888 

### ISSUE THREAD

**Issue by Eire-deerlet** [newbee-ltd/newbee-mall-api-go#3]
发生404错误，后端界面不是这个8888吗？

**Comment by Eire-deerlet** [comment]
> 发生404错误，后端界面不是这个8888吗？

**Comment by dalaohekele** [comment]
localhost:8888下没有对应的资源，可以尝试访问一下localhost:8888/api/v1/index-infos

**Comment by dalaohekele** [comment]
> 

localhost:8888下没有对应的资源，可以尝试访问一下localhost:8888/api/v1/index-infos
